### ISSUE TITLE
sample.npz lost

### ISSUE THREAD

**Issue by zhangjingxian1998** [GitBoSun/roomnet#16]
sample.npz lost, could you please reupload it?

**Comment by AmmaraRazzaq** [comment]
hi, 
did you find the sample.nz file?

**Comment by zhangjingxian1998** [comment]
> hi, did you find the sample.nz file?

sorry, I did not find sample.npz file then, but i find the sample.npz file will be generate by
https://github.com/GitBoSun/roomnet/blob/b1f8e7b9b41711819032f30f0f599388bd6f979f/roomnet/main.py#L96
maybe you can have try

**Comment by AmmaraRazzaq** [comment]
ok thanks, it means i will have to train my own model.
