### ISSUE TITLE
Mat file link is invalid

### ISSUE THREAD

**Issue by lingaimu** [GitBoSun/roomnet#9]
Hi!

The link[http://lsun.cs.princeton.edu/challenge/2015/roomlayout/data/training.mat]and  [http://lsun.cs.princeton.edu/challenge/2015/roomlayout/data/validation.mat]are invalid.When I searched for this link,the page displays "The requested URL  was not found on this server." Can you upload mat files to github?

Thank you very much!

**Comment by Jianbin-IBM** [comment]
same here.

**Comment by lingaimu** [comment]
Thank you for reply

**Comment by Jianbin-IBM** [comment]
> Thank you for reply

Hi, could you please upload the mat file? Thanks very much

**Comment by lingaimu** [comment]
> > 谢谢你的回复
> 
> 嗨，你能上传mat文件吗？非常感谢

your email

**Comment by alex-kravets** [comment]
Hi!
The same problem, can you update the link please? Or if you have a copy of those files, wouldn't you mind upload them then?

**Comment by DHNicoles** [comment]
> > > 谢谢你的回复
> > 
> > 
> > 嗨，你能上传mat文件吗？非常感谢
> 
> your email

I also encountered the same problem, missing the *mat file.
Below is my mailbox：
### **cgf_bupt@163.com**
Thank you so much!
